### PR TITLE
Fix typo : "of of" -> "of"

### PR DESCRIPTION
**Pull request by Thms-Brnrd**

### CODE REVIEW

**Comment by lachlanjc** [comment]
Hey there, thanks so much for contributing! The file you edited is the built page for the documentation, so you’ll need to edit the source code of the page first, then generate the built site as well. (We’re working on improving this, but for now it’s a bit of a pain.)

1. If you haven’t yet cloned the repo onto your computer and run `npm install`, do that now :wink:
2. Edit [src/templates/index.html](https://github.com/tachyons-css/tachyons-css.github.io/blob/master/src/templates/index.html#L316) on your branch, making the correction
3. Run `npm run doc` from your terminal
4. Push back up to this branch and let me know you’ve updated it

Let me know if you need any help, and thanks again! 😀

**Comment by Thms-Brnrd** [comment]
Hey! Oops, sorry, I missed the built files explanation in the README...
I hope it's complete this time ! 😉
Thanks for your time and the detailed procedure 😄

**Comment by lachlanjc** [comment]
🙌🏻! Thanks so much. I'm going to take another look at this on my computer later, but it should be good to go 😀

**Comment by Thms-Brnrd** [comment]
Hi ! Any update on this pull request ? 😉

**Comment by lachlanjc** [comment]
Sorry Thomas! This PR looks mergeable but when I look at the changes tab, it looks like you force-pushed and something went wrong. Could you take a look into that? Thanks :)
image

**Comment by Thms-Brnrd** [comment]
Sorry, I tried to solve this problem but closed the PR by mistake. I preferred to create a clean new one here : #65. I hope it will be fine this time, and sorry for the mess here...

**Comment by lachlanjc** [comment]
@Thms-Brnrd don't worry about it dude! everything's good and thanks for helping out :)

**Pull request closed without merging**
