### PR TITLE
Fix horizontal wobble.

### PR DESCRIPTION
**Pull request by DylanVann**
Site should not have horizontal scrolling.

### CODE REVIEW

**Comment by sebastienbarre** [comment]
@DylanVann Unfortunately this is not the right file. Everything in `components` is generated/built (we should really rename it to `build`, @mrmrs, this happens often in these PR). The source templates are in `src` (in this case, [here](https://github.com/tachyons-css/tachyons-css.github.io/blob/ff2ffe2bd127d4d620297855dbc362202fbad2cf/src/templates/components-index.html))

**Comment by DylanVann** [comment]
I'll find it, one minute.

**Comment by sebastienbarre** [comment]
Code looks good, but design concerns I leave to @mrmrs, who I added as reviewer. Thanks.

**Comment by DylanVann** [comment]
**wobble**

wobble

**no wobble**

no_wobble

**Comment by sebastienbarre** [comment]
Thanks for the GIF! Please yank our chain if no review is done by next week.

**Comment by DylanVann** [comment]
⛓ 👌🏻

Just checking my PRs and saw this one is still open. It's still an issue on the website.

I'm using tachyons on RN these days 😄

**Pull request closed without merging**
