### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Madmanden**
Fixed typos

### CODE REVIEW

**Comment by lachlanjc** [comment]
Hey @Madmanden, thanks so much for this fix! Quick thing — the file you edited is the source code for the documentation, but you have to generate the built site as well. The docs team is working on improving this, but for now you need to manually run `npm run doc` to regenerate the pages people will see. Let me know if you need any help 😀

Thanks again!

**Comment by Madmanden** [comment]
Thanks @lachlanjc! I'm still a bit new to this though... Do you mean I need to do the 'npm run doc' thing for you to merge the pull request, or do you mean if I'm running it locally? Sorry if that sounds silly. 😄

**Comment by lachlanjc** [comment]
@Madmanden Don't worry about it! So yes, you'll need to run that locally, commit + push, then I'll check over it and merge.

**Comment by Madmanden** [comment]
I tried doing npm run doc, and after installing some missing npm modules, it keeps failing:

`Error: Cannot find module 'tachyons-widths/package.json'

    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/1 TB 5400/Google Drev/Diverse/2016/Web dev/_Github/tachyons-css.github.io/src/modules/widths.js:9:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)`

It fails to find any tachyon modules.

**Comment by mrmrs** [comment]
This has been fixed with #59

**Pull request closed without merging**
