### PR TITLE
Custom build page

### LINKED ISSUE #43: Custom Build Page
This is an intentional dupe of issue #141 of [https://github.com/tachyons-css/tachyons](url), you can find it here: [https://github.com/tachyons-css/tachyons/issues/141](url)

We are going to create a page that will allow a user to download a "custom build" of tachyons that fits there purposes.  It will include the ability to select and deselect individual modules as well as categories such as typography or layout.  They can then download a CSS file that can be downloaded and built with `tachyons-cli` and used in your production apps.

@mrmrs Says he will provide categorization
I will write the code.  Any criteria that need to be followed should be put here.

In a discussion with @johnotander in the original issue we determined to

- Use whatever framework / library the contributors feel fit the usecase
- Handle all functionality on the front end.  NO BACK END if possible

Once I feel the spec is pretty well mapped out, I'll begin work on my fork.  I'll try to be transparent about big decisions here, and have more discussions in the Slack.  My username is `anthonybullard` there.  So Hi :-)

### PR DESCRIPTION
**Pull request by gamebox**
This closes #43 

@mrmrs plans on touching up the aesthetics and the copy.

### CODE REVIEW

**Comment by gamebox** [comment]
I know that you have a lot going on, but is there something I can do to help move this along @mrmrs or @johnotander ?  I'm scared of losing a lot of context when you ask for changes here.

**Comment by johnotander** [comment]
Sorry about the delay on this @gamebox.

I know that @mrmrs wants to do some design-age and tweak the messaging before going "live". But I'd imagine to start we could merge in the page without a link in the nav. This will allow us to soak it a bit and make sure it all works before adding a link for all users to see.

**Comment by gamebox** [comment]
That sounds like a good approach.  I'll add a commit to remove the link tomorrow morning and add it to the PR

**Comment by mrmrs** [comment]
Hey Anthony,
I'd say let's just leave it unmerged right now. I just got internet in my apartment so trying to catch up on lots of oss things. I hate to have you undo work or do unnecessary work by making a commit just to remove the link. I understand you don't want to lose context, but I also don't like to ship things without working on copy or visual design. My deepest apologies for being behind on this, open source efforts on my end generally come in waves. Definitely appreciate your help with this. Remember: any requested changes made will just become new issues. There is no pressure or obligation on your part to do them :)

**Comment by mrmrs** [comment]
This has been moved to a separate PR.

**Pull request closed without merging**
