### PR TITLE
Add alt text to images in Components & Docs

### PR DESCRIPTION
**Pull request by donnieberg**
@mrmrs Updated files in `src/` this time. I didn't include the generated files in this PR but let me know if I should.

### CODE REVIEW

**Comment by donnieberg** [comment]
@mrmrs Turns out the Example Links in the Docs just needed focus classes.

**Comment by johnotander** [comment]
Looks like there is a merge conflict with this PR now, if you resolve it I can merge. Thanks!

**Comment by donnieberg** [comment]
Resolved :)

**Comment by johnotander** [comment]
Thanks!

**Comment by mrmrs** [comment]
ACCESSIBILITY!!! This makes me so excited.

**Pull request merged**
