### PR TITLE
Remove Bad Apostrophes

### PR DESCRIPTION
**Pull request by curtisgibby**
A possessive belonging to an "it" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!

### CODE REVIEW

**Comment by lachlanjc** [comment]
Hey @curtisgibby, thanks so much for this fix! Quick thing — the file you edited is the source code for the documentation, but you have to generate the built site as well. The docs team is working on improving this, but for now you need to manually run `npm run doc` to regenerate the pages people will see. Let me know if you need any help 😀

Thanks again!

**Comment by curtisgibby** [comment]
Updated the docs via the `npm run doc` command. That updated a bunch of other stuff, which doesn't seem quite kosher... but I guess you can take it or leave it.

**Comment by lachlanjc** [comment]
Thanks @curtisgibby! I would say this is fine (the docs grow out of date if we don't rebuild them frequently), but @mrmrs could you take a quick look before squashing and merging?

**Comment by mrmrs** [comment]
This has been merged in from #59

**Pull request closed without merging**
