### PR TITLE
Tweak visual styles on position examples

### PR DESCRIPTION
**Pull request by lachlanjc**
This PR is also purely visual styling changes, this time for the position page.

Before:
screenshot 2016-03-25 00 21 58

After:
screenshot 2016-03-25 00 21 43

### CODE REVIEW

**Comment by mrmrs** [comment]
So I go back and forth on this a bit - on whether to add padding because then it doesn't show it is positioned absolutely to be flush. Maybe worth putting a background color on there to show?

**Comment by lachlanjc** [comment]
I'll just remove the margin, so it'll be rounded but flush. Good call.

**Comment by lachlanjc** [comment]
Just removed the margin — the X is flush now with the upper-right corner.

**Comment by lachlanjc** [comment]
@mrmrs 👋 😉

**Comment by mrmrs** [comment]
After thinking about this for quite a bit I want to leave it as is. I want to visually indicate that the element is flush and want to do a good job of showing how one thing does one thing. We aren't perfect at this yet - I really waffle back and forth to be honest. Open to revisiting but want it to stay as is for now. 

Note, I might be wrong here. Just my gut.

**Pull request closed without merging**
