### PR TITLE
Add alt text to images in comonents and docs

### PR DESCRIPTION
**Pull request by donnieberg**
I added descriptive alt text to every image in the components and docs.

According to WebAIM, every image must have an alt attribute. It can be a blank string if the image is just a background and doesn't convey any real meaning (ie. `alt=""`).
http://webaim.org/techniques/alttext/

@mrmrs Have a look and let me know what you think.

### CODE REVIEW

**Comment by mrmrs** [comment]
@donnieberg This is great! This makes me realize we should have much better contributing documentation. Right now all of the files you edited are generated from the src/components/ directory - so I'll port these changes over to the source so they don't get overwritten next time someone changes them. Thanks!

**Comment by donnieberg** [comment]
Doh! Makes total sense. What do you think about moving `components/` and `docs/` into a `dist/` folder to make it super clear they're generated files.

**Comment by johnotander** [comment]
> What do you think about moving components/ and docs/ into a dist/ folder to make it super clear they're generated files?

:100:. I've been meaning to overhaul the layout of the src/built pages so that things are more clear/straightforward. I'm going to work on adding real documentation to the readme this afternoon to add more description and context as well.

**Comment by mrmrs** [comment]
@donnieberg @johnotander - So my only beef (and correct me if I am wrong) - is that then the URL structure will have dist/docs/ dist/components for the site which I don't want. Would like to just have a simple URL structure. I think we can solve the problem just by making it super clear in the docs (and maybe have a bot that lets people know if they only edit a compiled file?) Anyways just my quick thoughts.

**Comment by johnotander** [comment]
Yeah, that definitely makes sense, would be preferable to avoid the `dist` url segment. We can run with the first step of adding documentation and see if that is sufficient or not.

**Comment by donnieberg** [comment]
Adding documentation sounds good to me! If there's confusion later on, we could think about moving the generated `index.html` to `dist/` and serve up that entire folder. But I agree that simplicity is better to begin with :)

**Pull request closed without merging**
